---
name: parrot
version: 0.4.12
author: ~
abstract: ~
license: perl
no_index:
    directory:
        - config
        - languages
        - lib/Class
        - lib/Digest
        - lib/File
        - lib/Parse
        - lib/Pod
        - lib/Test
        - lib/Text
        - t
        - tools
    file:
        - lib/SmartLink.pm
    package:
        - DB
        - Parrot::Test::DB
        - Parrot::Distribution
        - Parrot::Docs::HTMLPage
        - Parrot::OpTrans::CGP
        - Parrot::OpTrans::CSwitch
        - Parrot::OpTrans::Compiled
        - Perl::Critic::Policy::CodeLayout::UseParrotCoda
        - Parrot::OpsFile
    namespace:
        - Parrot::Configure
resources:
    homepage: http://parrotcode.org/
    bugtracker: https://rt.perl.org/rt3/
generated_by: Humans
