# $Id$
#
# This file describes the CPAN distribution for Parrot.
# See http://module-build.sourceforge.net/META-spec-current.html for details.
---
name: parrot
version: 0.7.0
author: parrot-porters@perl.org
abstract: a virtual machine designed for dynamic languages
license: artistic2
no_index:
    directory:
        - config
        - languages
        - lib/Digest
        - lib/File
        - lib/Parse
        - lib/Perl/Critic
        - lib/Pod
        - t
        - tools
    file:
        - lib/IO/CaptureOutput.pm
        - lib/SmartLink.pm
    package:
        - DB
        - Parrot::Test::DB
        - Parrot::Distribution
        - Parrot::Docs::HTMLPage
        - Parrot::OpTrans::CGP
        - Parrot::OpTrans::CSwitch
        - Parrot::OpTrans::Compiled
        - Parrot::OpsFile
resources:
    homepage:   'http://parrotcode.org/'
    license:    'http://opensource.org/licenses/artistic-license-2.0.php'
    bugtracker: 'https://rt.perl.org/rt3/'
generated_by: Humans
